<?php

namespace Database\Seeders;

use App\Models\Activity;
use Illuminate\Database\Seeder;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $activities = [
            // Giza Activities
            [
                'name' => 'Camel Ride at Pyramids',
                'description' => 'Experience the ancient pyramids from a camel\'s back, just like the pharaohs did thousands of years ago.',
                'location' => 'Giza, Egypt',
                'country' => 'Egypt',
                'city' => 'Giza',
                'rating' => 4.7,
                'price_range' => ['min' => 25, 'max' => 50],
                'duration_hours' => 2,
                'category' => 'Adventure',
                'image' => 'https://images.unsplash.com/photo-1552083375-1447ce886485?w=800&h=600&fit=crop',
                'highlights' => ['Camel ride', 'Pyramid views', 'Photo opportunities', 'Local guide'],
                'included_services' => ['Camel ride', 'Local guide', 'Photos', 'Water'],
                'excluded_services' => ['Tips', 'Personal expenses'],
                'what_to_bring' => ['Comfortable clothes', 'Sunscreen', 'Camera'],
                'best_time_to_visit' => 'Early morning or sunset',
                'difficulty_level' => 'easy',
                'min_age' => 5,
                'max_group_size' => 10,
                'views' => 1500,
                'is_popular' => true,
                'is_recommended' => true,
            ],
            [
                'name' => 'Sound and Light Show at Pyramids',
                'description' => 'Witness the magical sound and light show that brings the pyramids to life with stunning visual effects.',
                'location' => 'Giza, Egypt',
                'country' => 'Egypt',
                'city' => 'Giza',
                'rating' => 4.5,
                'price_range' => ['min' => 30, 'max' => 60],
                'duration_hours' => 1,
                'category' => 'Entertainment',
                'image' => 'https://images.unsplash.com/photo-1503177119275-0aa32b3fb369?w=800&h=600&fit=crop',
                'highlights' => ['Spectacular light show', 'Historical narration', 'Evening experience', 'Pyramid backdrop'],
                'included_services' => ['Show ticket', 'Audio guide', 'Seating'],
                'excluded_services' => ['Transportation', 'Food and drinks'],
                'what_to_bring' => ['Warm clothes', 'Camera', 'Patience'],
                'best_time_to_visit' => 'Evening (7:00 PM)',
                'difficulty_level' => 'easy',
                'min_age' => 3,
                'max_group_size' => 100,
                'views' => 1200,
                'is_popular' => true,
                'is_recommended' => true,
            ],
            [
                'name' => 'Pyramid Interior Tour',
                'description' => 'Explore the mysterious interior of the Great Pyramid, including the King\'s Chamber and Grand Gallery.',
                'location' => 'Giza, Egypt',
                'country' => 'Egypt',
                'city' => 'Giza',
                'rating' => 4.8,
                'price_range' => ['min' => 40, 'max' => 80],
                'duration_hours' => 3,
                'category' => 'Historical',
                'image' => 'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=800&h=600&fit=crop',
                'highlights' => ['Interior exploration', 'Ancient architecture', 'Historical insights', 'Unique experience'],
                'included_services' => ['Entry ticket', 'Expert guide', 'Safety equipment'],
                'excluded_services' => ['Photos inside', 'Personal items'],
                'what_to_bring' => ['Comfortable shoes', 'Light clothes', 'Water'],
                'best_time_to_visit' => 'Morning (less crowded)',
                'difficulty_level' => 'moderate',
                'min_age' => 12,
                'max_group_size' => 15,
                'views' => 800,
                'is_popular' => false,
                'is_recommended' => true,
            ],

            // Luxor Activities
            [
                'name' => 'Hot Air Balloon over Valley of Kings',
                'description' => 'Soar above the ancient Valley of the Kings in a hot air balloon for breathtaking views of the Nile and monuments.',
                'location' => 'Luxor, Egypt',
                'country' => 'Egypt',
                'city' => 'Luxor',
                'rating' => 4.9,
                'price_range' => ['min' => 120, 'max' => 200],
                'duration_hours' => 4,
                'category' => 'Adventure',
                'image' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
                'highlights' => ['Aerial views', 'Sunrise experience', 'Professional pilot', 'Safety briefing'],
                'included_services' => ['Balloon flight', 'Breakfast', 'Transportation', 'Certificate'],
                'excluded_services' => ['Personal insurance', 'Tips'],
                'what_to_bring' => ['Warm clothes', 'Camera', 'Comfortable shoes'],
                'best_time_to_visit' => 'Sunrise (5:00 AM)',
                'difficulty_level' => 'easy',
                'min_age' => 8,
                'max_group_size' => 20,
                'views' => 2000,
                'is_popular' => true,
                'is_recommended' => true,
            ],
            [
                'name' => 'Nile River Cruise',
                'description' => 'Enjoy a relaxing cruise on the Nile River with traditional Egyptian music and dinner.',
                'location' => 'Luxor, Egypt',
                'country' => 'Egypt',
                'city' => 'Luxor',
                'rating' => 4.6,
                'price_range' => ['min' => 60, 'max' => 120],
                'duration_hours' => 3,
                'category' => 'Relaxation',
                'image' => 'https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800&h=600&fit=crop',
                'highlights' => ['Nile views', 'Traditional music', 'Dinner', 'Sunset'],
                'included_services' => ['Cruise ticket', 'Dinner', 'Entertainment', 'Drinks'],
                'excluded_services' => ['Alcoholic drinks', 'Tips'],
                'what_to_bring' => ['Smart casual clothes', 'Camera', 'Light jacket'],
                'best_time_to_visit' => 'Sunset (6:00 PM)',
                'difficulty_level' => 'easy',
                'min_age' => 3,
                'max_group_size' => 50,
                'views' => 1800,
                'is_popular' => true,
                'is_recommended' => true,
            ],

            // Cairo Activities
            [
                'name' => 'Khan El Khalili Market Tour',
                'description' => 'Explore the historic Islamic market with traditional crafts, spices, and authentic Egyptian souvenirs.',
                'location' => 'Cairo, Egypt',
                'country' => 'Egypt',
                'city' => 'Cairo',
                'rating' => 4.4,
                'price_range' => ['min' => 20, 'max' => 40],
                'duration_hours' => 4,
                'category' => 'Cultural',
                'image' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
                'highlights' => ['Traditional market', 'Local crafts', 'Spice shops', 'Cultural experience'],
                'included_services' => ['Local guide', 'Market tour', 'Shopping assistance'],
                'excluded_services' => ['Purchases', 'Food and drinks'],
                'what_to_bring' => ['Comfortable shoes', 'Cash', 'Bargaining skills'],
                'best_time_to_visit' => 'Morning or evening',
                'difficulty_level' => 'easy',
                'min_age' => 5,
                'max_group_size' => 12,
                'views' => 1100,
                'is_popular' => true,
                'is_recommended' => false,
            ],
            [
                'name' => 'Egyptian Museum Guided Tour',
                'description' => 'Discover the world\'s largest collection of ancient Egyptian artifacts with expert guidance.',
                'location' => 'Cairo, Egypt',
                'country' => 'Egypt',
                'city' => 'Cairo',
                'rating' => 4.7,
                'price_range' => ['min' => 35, 'max' => 70],
                'duration_hours' => 3,
                'category' => 'Educational',
                'image' => 'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=800&h=600&fit=crop',
                'highlights' => ['Tutankhamun treasures', 'Ancient artifacts', 'Expert guide', 'Historical insights'],
                'included_services' => ['Museum entry', 'Expert guide', 'Audio guide'],
                'excluded_services' => ['Photos', 'Personal expenses'],
                'what_to_bring' => ['Comfortable shoes', 'Camera', 'Water'],
                'best_time_to_visit' => 'Morning (less crowded)',
                'difficulty_level' => 'easy',
                'min_age' => 8,
                'max_group_size' => 15,
                'views' => 1600,
                'is_popular' => true,
                'is_recommended' => true,
            ],

            // Aswan Activities
            [
                'name' => 'Philae Temple Visit',
                'description' => 'Visit the beautiful Philae Temple dedicated to the goddess Isis, located on an island in the Nile.',
                'location' => 'Aswan, Egypt',
                'country' => 'Egypt',
                'city' => 'Aswan',
                'rating' => 4.6,
                'price_range' => ['min' => 30, 'max' => 60],
                'duration_hours' => 2,
                'category' => 'Historical',
                'image' => 'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=800&h=600&fit=crop',
                'highlights' => ['Island temple', 'Nile views', 'Ancient architecture', 'Boat ride'],
                'included_services' => ['Temple entry', 'Boat ride', 'Guide'],
                'excluded_services' => ['Tips', 'Personal expenses'],
                'what_to_bring' => ['Comfortable clothes', 'Camera', 'Sunscreen'],
                'best_time_to_visit' => 'Morning or late afternoon',
                'difficulty_level' => 'easy',
                'min_age' => 5,
                'max_group_size' => 20,
                'views' => 900,
                'is_popular' => false,
                'is_recommended' => true,
            ],

            // Red Sea Activities
            [
                'name' => 'Scuba Diving in Red Sea',
                'description' => 'Explore the vibrant coral reefs and marine life in the crystal-clear waters of the Red Sea.',
                'location' => 'Hurghada, Egypt',
                'country' => 'Egypt',
                'city' => 'Hurghada',
                'rating' => 4.9,
                'price_range' => ['min' => 80, 'max' => 150],
                'duration_hours' => 6,
                'category' => 'Adventure',
                'image' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop',
                'highlights' => ['Coral reefs', 'Marine life', 'Professional instructor', 'Equipment provided'],
                'included_services' => ['Diving equipment', 'Instructor', 'Boat trip', 'Lunch'],
                'excluded_services' => ['Personal insurance', 'Tips'],
                'what_to_bring' => ['Swimsuit', 'Towel', 'Sunscreen'],
                'best_time_to_visit' => 'Year-round (best: March-November)',
                'difficulty_level' => 'moderate',
                'min_age' => 12,
                'max_group_size' => 8,
                'views' => 2500,
                'is_popular' => true,
                'is_recommended' => true,
            ],

            // Additional Activities for more variety
            [
                'name' => 'Desert Safari in White Desert',
                'description' => 'Experience the surreal White Desert with its unique chalk rock formations and overnight camping.',
                'location' => 'Farafra, Egypt',
                'country' => 'Egypt',
                'city' => 'Farafra',
                'rating' => 4.7,
                'price_range' => ['min' => 150, 'max' => 300],
                'duration_hours' => 24,
                'category' => 'Adventure',
                'image' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
                'highlights' => ['Desert camping', 'Rock formations', 'Stargazing', 'Bedouin experience'],
                'included_services' => ['4x4 vehicle', 'Camping equipment', 'Meals', 'Guide'],
                'excluded_services' => ['Personal items', 'Sleeping bag'],
                'what_to_bring' => ['Warm clothes', 'Camera', 'Personal toiletries'],
                'best_time_to_visit' => 'October to April',
                'difficulty_level' => 'moderate',
                'min_age' => 10,
                'max_group_size' => 15,
                'views' => 1200,
                'is_popular' => true,
                'is_recommended' => true,
            ],
            [
                'name' => 'Mount Sinai Sunrise Climb',
                'description' => 'Climb Mount Sinai at sunrise and visit the historic St. Catherine Monastery.',
                'location' => 'Sinai Peninsula, Egypt',
                'country' => 'Egypt',
                'city' => 'Saint Catherine',
                'rating' => 4.8,
                'price_range' => ['min' => 100, 'max' => 200],
                'duration_hours' => 12,
                'category' => 'Adventure',
                'image' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
                'highlights' => ['Sunrise views', 'Mountain climbing', 'Monastery visit', 'Religious significance'],
                'included_services' => ['Guide', 'Transportation', 'Breakfast', 'Entry fees'],
                'excluded_services' => ['Personal equipment', 'Tips'],
                'what_to_bring' => ['Warm clothes', 'Hiking shoes', 'Water', 'Camera'],
                'best_time_to_visit' => 'Early morning (2:00 AM start)',
                'difficulty_level' => 'challenging',
                'min_age' => 14,
                'max_group_size' => 20,
                'views' => 1800,
                'is_popular' => true,
                'is_recommended' => true,
            ],
            [
                'name' => 'Nubian Village Cultural Experience',
                'description' => 'Immerse yourself in Nubian culture with traditional music, local cuisine, and authentic village life.',
                'location' => 'Aswan, Egypt',
                'country' => 'Egypt',
                'city' => 'Aswan',
                'rating' => 4.5,
                'price_range' => ['min' => 40, 'max' => 80],
                'duration_hours' => 6,
                'category' => 'Cultural',
                'image' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
                'highlights' => ['Traditional music', 'Local cuisine', 'Village tour', 'Cultural exchange'],
                'included_services' => ['Village tour', 'Traditional meal', 'Music performance', 'Guide'],
                'excluded_services' => ['Personal purchases', 'Tips'],
                'what_to_bring' => ['Comfortable clothes', 'Camera', 'Open mind'],
                'best_time_to_visit' => 'Morning or afternoon',
                'difficulty_level' => 'easy',
                'min_age' => 5,
                'max_group_size' => 12,
                'views' => 800,
                'is_popular' => false,
                'is_recommended' => true,
            ],
            [
                'name' => 'Coptic Cairo Churches Tour',
                'description' => 'Explore the ancient Coptic Christian heritage of Cairo, including the Hanging Church and Coptic Museum.',
                'location' => 'Cairo, Egypt',
                'country' => 'Egypt',
                'city' => 'Cairo',
                'rating' => 4.3,
                'price_range' => ['min' => 25, 'max' => 50],
                'duration_hours' => 4,
                'category' => 'Historical',
                'image' => 'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=800&h=600&fit=crop',
                'highlights' => ['Ancient churches', 'Coptic museum', 'Religious history', 'Architecture'],
                'included_services' => ['Entry fees', 'Guide', 'Transportation'],
                'excluded_services' => ['Personal expenses', 'Tips'],
                'what_to_bring' => ['Modest clothing', 'Camera', 'Comfortable shoes'],
                'best_time_to_visit' => 'Morning (less crowded)',
                'difficulty_level' => 'easy',
                'min_age' => 8,
                'max_group_size' => 15,
                'views' => 600,
                'is_popular' => false,
                'is_recommended' => false,
            ],
        ];

        foreach ($activities as $activity) {
            Activity::create($activity);
        }

        $this->command->info('Activities seeded successfully.');
    }
};
